# Site settings
title: The Northridge Plumber
email: robert@robertsplumbing.net
phone: 1 (818) 298 - 1344
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/thenorthridgeplumber.com" # the subpath of your site, e.g. /blog/
# url: "http://thenorthridgeplumber.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
gems:
- bourbon